#pragma once

#include "Command.h"
#include "CommandVisitor.h"

#include "Operations.h"
#include "TextOption.h"

#include "SkipCommand.h"
#include "EndScriptCommand.h"
#include "BackgroundLoadCommand.h"
#include "SetImageCommand.h"
#include "ChoiceCommand.h"
#include "JumpCommand.h"
#include "DelayCommand.h"
#include "RandomCommand.h"
#include "LabelCommand.h"
#include "GoToCommand.h"
#include "ClearTextCommand.h"
#include "IfCommand.h"
#include "FiCommand.h"
#include "AwaitInputCommand.h"
#include "TextCommand.h"
#include "SetLocalVariableCommand.h"
#include "ClearLocalVariablesCommand.h"
#include "SetGlobalVariableCommand.h"
#include "ClearGlobalVariablesCommand.h"
#include "PlayMusicCommand.h"
#include "StopMusicCommand.h"
#include "PlaySoundCommand.h"
#include "StopSoundCommand.h"